[supabase]
SUPABASE_URL = "https://fqolgchelzejkbrbhrch.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxb2xnY2hlbHplamticmJocmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1ODkwNTEsImV4cCI6MjEwNjE2NTA1MX0.WH8OfOkt4VdWadtCVA3gqF1TPMCrNfxFH5dWL2j3gXk"
[backend]
url = "https://hiremind-ai-hf.onrender.com"